---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameofblocks-__CI_ENVIRONMENT_SLUG__
  labels:
    app: gameofblocks
    ref: __CI_ENVIRONMENT_SLUG__
    track: stable
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gameofblocks
      ref: __CI_ENVIRONMENT_SLUG__
  template:
    metadata:
      labels:
        app: gameofblocks
        ref: __CI_ENVIRONMENT_SLUG__
        track: stable
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: app
          image: __CI_REGISTRY_IMAGE__/app:__CI_COMMIT_SHA__
          imagePullPolicy: Always
          env:
            - name: AUTH0_DOMAIN
              value: 'Hello from the environment'
            - name: AUTH0_CLIENT_ID
              value: 'Such a sweet sorrow'
            - name: AUTH0_CLIENT_SECRET
              value: 'Such a sweet sorrow'
          ports:
            - name: http-metrics
              protocol: TCP
              containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            timeoutSeconds: 2
