---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameofblocks-${CI_ENVIRONMENT_SLUG}
  labels:
    app: gameofblocks
    ref: ${CI_ENVIRONMENT_SLUG}
    track: stable
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gameofblocks
      ref: ${CI_ENVIRONMENT_SLUG}
  template:
    metadata:
      labels:
        app: gameofblocks
        ref: ${CI_ENVIRONMENT_SLUG}
        track: stable
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: app
          image: ${CI_REGISTRY_IMAGE}/app:${CI_COMMIT_SHA}
          imagePullPolicy: Always
          env:
            - name: AUTH0_DOMAIN
              value: ${AUTH0_DOMAIN}
            - name: AUTH0_CLIENT_ID
              value: ${AUTH0_CLIENT_ID}
            - name: AUTH0_CLIENT_SECRET
              value: ${AUTH0_CLIENT_SECRET}
            - name: AUTH0_CALLBACK_URL
              value: 'http://test.tototo'
            - name: APP_PORT
              value: '${APP_PORT}'
          ports:
            - name: http-metrics
              protocol: TCP
              containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            timeoutSeconds: 2
