apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gameofblocks-app-${CI_COMMIT_REF_SLUG}
  namespace: gameofblocks
  labels:
    app: ${CI_COMMIT_REF_SLUG}
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - ${CI_COMMIT_REF_SLUG}.dev.gameofblocks.io
    # the secret used here is an unsigned wildcard cert for demo purposes
    # use your own or comment this out
    secretName: tls-wildcard-demo
  rules:
  - host: ${CI_COMMIT_REF_SLUG}.dev.gameofblocks.io
    http:
      paths:
      - path: /
        backend:
          serviceName: gameofblocks-app-${CI_COMMIT_REF_SLUG}
          servicePort: 8000