variables:
  # CI variables
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  GIT_STRATEGY: fetch
  GIT_DEPTH: 5
  
  # Globals
  DOCKER_VERSION: "18"
  PYTHON_VERSION: "3.6-alpine"

stages:
- "Prepare"
- "Build Image"

.prepare_stage:
  stage: "Prepare"
  dependencies: []

.base_yarn_workspace_install:
  extends: .prepare_stage
  image: node:13-alpine
  interruptible: true
  script:
    - "[[ type jq ]] || apk add jq=~1"
    - apk add --no-cache python make g++
    - "{ rm package.json; jq 'del(.dependencies) | del(.devDependencies)' > package.json; } < package.json"

    - yarn config set cache-folder $CI_PROJECT_DIR/.yarn
    - yarn --frozen-lockfile

################################################################################################
###################################               ##############################################
###################################     PREPARE   ##############################################
###################################               ##############################################
################################################################################################


Install api:
  extends: .base_yarn_workspace_install
  variables:
    CONTEXT: api
  before_script:
    - find packages -maxdepth 1 -type d -not -name api -not -name knex | tail -n +2 | xargs rm -rf
  artifacts:
    expire_in: 1 day
    paths:
      - node_modules
      - packages/api/node_modules

Install app:
  extends: .base_yarn_workspace_install
  variables:
    CONTEXT: app
  before_script:
    - find packages -maxdepth 1 -type d -not -name app | tail -n +2 | xargs rm -rf
  artifacts:
    expire_in: 1 day
    paths:
      - node_modules
      - packages/app/node_modules

################################################################################################
###################################                    #########################################
###################################     BUILD IMAGE    #########################################
###################################                    #########################################
################################################################################################

Build @gameofblocks/app:
  stage: "Build Image"
  variables:
    INVALID_GIT_FILES_CHANGES: "true"
  dependencies:
    - Install app
  needs:
    - Install app
  image: node:12-alpine
  script:
    - yarn workspace @gameofblocks/app build
  artifacts:
    expire_in: 1 day
    paths:
      - packages/app/.next