variables:
  # CI variables
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ''
  GIT_STRATEGY: fetch
  GIT_DEPTH: 5

  # Globals
  DOCKER_VERSION: '18'
  PYTHON_VERSION: '3.6-alpine'

stages:
  - test

test:
  image:
    name: lachlanevenson/k8s-kubectl:latest
    entrypoint: ['/bin/sh', '-c']
  stage: test
  before_script:
    - apk add --update -t deps curl
  script:
    - kubectl version
    - echo $CI_BUILD_REF_NAME
    - echo "$CI_REGISTRY_IMAGE/app:$CI_COMMIT_SHA"
    - echo $CI_REGISTRY
    - echo $CI_COMMIT_REF_SLUG
    - echo https://${CI_ENVIRONMENT_SLUG}.dev.gameofblocks.io
    - echo $CI_REGISTRY_IMAGE
    - echo $CI_COMMIT_SHA
    - echo $DIGITAL_OCEAN_TOKEN
    - echo $CURL_HEADERS
    - echo $CURL_BODY
    - echo $CURL_REQUEST
    - |-
      curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${DIGITAL_OCEAN_TOKEN}" -d '{"name": "${CI_COMMIT_REF_SLUG}"}' "https://api.digitalocean.com/v2/databases/${DATA_BASE_ID}/dbs"
