version: "3"

services:
  db:
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5434:5432"
    volumes:
      - gameofblocks-pgdata:/var/lib/postgresql/data

  hasura:
    image: hasura/graphql-engine:v1.1.0
    ports:
      - 5000:8080
    depends_on:
      - db
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_ADMIN_SECRET: $HASURA_SECRET
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS256","jwk_url": "$DOCKER_HOST_URL:$API_PORT/auth/jwks"}'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: 'anonymous'

volumes:
  gameofblocks-pgdata:
