apiVersion: v1
name: nodejs
version: 3.0.1
appVersion: 1.0
home: https://github.com/SocialGouv/helm-charts/tree/master/charts/nodejs
description: Social Gouv NodeJS Helm chart for Kubernetes
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Node.js_logo.svg/200px-Node.js_logo.svg.png
keywords:
  - nodejs
sources:
  - https://github.com/SocialGouv/helm-charts/tree/master/charts/nodejs
maintainers:
  - name: Incubateur des Ministères Sociaux
    email: dsi-incubateur@sg.social.gouv.fr
