# Default values for nodejs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


image:
  repository: registry.gitlab.com/gameofblock/gameofblocks/app
  tag: ${IMAGE_TAG}
  pullPolicy: IfNotPresent

# Global labels
labels: {}
  # owner: default # where the project is in the cluster
  # team: helm-charts # the github "team" or repo name

deployment:

  annotations: {}
  # app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
  # app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}

  replicaCount: 1
  imagePullSecrets: []

  port: 80

  livenessProbe:
    initialDelaySeconds: 5
    path: /
    port: 80
    periodSeconds: 3
    failureThreshold: 3
    timeoutSeconds: 5
  readinessProbe:
    initialDelaySeconds: 5
    path: /
    port: 80
    periodSeconds: 3
    failureThreshold: 3
    timeoutSeconds: 5
  resources:
    limits:
      cpu: 250m
      memory: 768Mi
    requests:
      cpu: 10m
      memory: 512Mi

  env:
  - name: PORT
    value: "80"

  nodeSelector: {}

  tolerations: []

  affinity: {}

  initContainers: []

ingress:
  enabled: true
  annotations:
  hosts:
    - host: dev.gameofblocks.io
      paths:
        - path: /
          servicePort: ${PORT}
  tls:
    - hosts:
        - dev.gameofblocks.io
      secretName: app-certificate


fullnameOverride: ""
nameOverride: ""

service:
  type: ClusterIP
  port: ${PORT}
  targetPort: ${PORT}

