---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasura-gameofblocks-${CI_ENVIRONMENT_SLUG}
  labels:
    app: hasura-gameofblocks
    ref: hasura-${CI_ENVIRONMENT_SLUG}
    track: stable
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hasura-gameofblocks
      ref: hasura-${CI_ENVIRONMENT_SLUG}
  template:
    metadata:
      labels:
        app: hasura-gameofblocks
        ref: hasura-${CI_ENVIRONMENT_SLUG}
        track: stable
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: app
          image: ${CI_REGISTRY_IMAGE}/hasura:${CI_COMMIT_SHA}
          imagePullPolicy: Always
          env:
            - name: PGSSLMODE
              value: 'require'
            - name: HASURA_GRAPHQL_PG_CONNECTIONS
              value: '6'
            - name: HASURA_GRAPHQL_DATABASE_URL
              value: postgres://${POSTGRES_PASSWORD}:${POSTGRES_PASSWORD}@gameofblocks-do-user-6394442-0.a.db.ondigitalocean.com:25060/${$CI_COMMIT_REF_SLUG}?sslmode=require
            - name: HASURA_GRAPHQL_ADMIN_SECRET
              value: ${HASURA_SECRET}
            - name: HASURA_GRAPHQL_ENABLE_CONSOLE
              value: 'true'
          ports:
            - name: http-metrics
              protocol: TCP
              containerPort: 8080
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 80
          #   initialDelaySeconds: 3
          #   timeoutSeconds: 2
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 80
          #   initialDelaySeconds: 3
          #   timeoutSeconds: 2
