image:
  repository: registry.gitlab.com/gameofblock/gameofblocks/app
  tag: latest

deployment:
  resources:
    limits:
      cpu: 250m
      memory: 768Mi
    requests:
      cpu: 10m
      memory: 512Mi

  env:
  - name: PORT
    value: "80"
    
service:
  port: ${PORT}
  targetPort: ${PORT}

ingress:
  enabled: true
  annotations:
  hosts:
    - host: dev.gameofblocks.io
      paths:
        - path: /
          servicePort: ${PORT}
  tls:
    - hosts:
        - dev.gameofblocks.io
      secretName: app-certificate
